# app.yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: kubevela-demo-app
spec:
  components:
    - name: kubevela-demo-app-web
      type: webservice
      properties:
        image: samira1/kubevela-demo-cicd-app
        imagePullPolicy: Always
        port: 8181
      traits:
        - type: rollout
          properties:
            rolloutBatches:
              - replicas: 2
              - replicas: 3
            batchPartition: 0
            targetSize: 5
        - type: labels
          properties:
            jenkins-build-commit: GIT_COMMIT
        - type: ingress
          properties:
            domain: kubevela-demo-cicd-app.04c9449af93d7b32232381cf9f184f0ee08267c4dc91b602bfc9aa0558c25dc9.us-west-1.alicontainer.com
            http:
              "/": 8088
